version: 2 
jobs: 
  build:
    docker:
      - image: circleci/golang:1.13 
    working_directory: /go/src/github.com/vinli/cronexpr
    steps: 
      - checkout 
      - run:
          name: Run unit tests
          command: |
            go test ./...